name       : mpc-client
version    : '0.33'
release    : 6
homepage   : https://www.musicpd.org/clients/mpc/
source     :
    - https://github.com/MusicPlayerDaemon/mpc/archive/v0.33.tar.gz : ee87e6f83bc9039172fc48e70b3803b212d82264b17ec433881cc5ee80ed1b95
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A minimalist command line interface to MPD
description: |
    A minimalist command line interface to MPD.
builddeps  :
    - pkgconfig(check)          # tests
    - pkgconfig(libmpdclient)
    - python-sphinx
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-build-html-doc.patch

    %meson_configure -Dtest=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -dm00755 $installdir/usr/share/bash-completion/completions
    mv $installdir/usr/share/doc/mpc/contrib/mpc-completion.bash $installdir/usr/share/bash-completion/completions/mpc
check      : |
    %ninja_check
