name       : mpc-client
version    : '0.28'
release    : 5
homepage   : http://www.musicpd.org/clients/mpc/
source     :
    - https://github.com/MusicPlayerDaemon/mpc/archive/v0.28.tar.gz : 3197a15754d0a8d1200ec277b72b0803db9040e580ba0299415e92301d899f96
license    : GPL-2.0
component  : multimedia.audio
summary    : A minimalist command line interface to MPD.
description: |
    A minimalist command line interface to MPD.
builddeps  :
    - pkgconfig(libmpdclient)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -Dm644 doc/mpc-completion.bash "$installdir/usr/share/bash-completion/completions/mpc"
