name        : mpc-client
version     : 0.27
release     : 1
homepage    : http://www.musicpd.org/clients/mpc/
source      :
    - http://www.musicpd.org/download/mpc/0/mpc-0.27.tar.xz : 45a2be0a6dea65ed43f631294c24e74b83c8ee66d1ba6ab47d0744ddb1e62064
license     : GPL-2.0
summary     : A minimalist command line interface to MPD.
description : |
    A minimalist command line interface to MPD.
builddeps   :
    - pkgconfig(libmpdclient)
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
    install -Dm644 doc/mpc-completion.bash "$installdir/usr/share/bash-completion/completions/mpc"
